services:
  auth:
    ports:
      - "5050:5050"
    volumes:
      - ./config/proxy.conf:/etc/nginx/templates/default.conf.template:ro
      - ./auth/.env:/opt/app/dist/.env:ro
    environment:
      TOKEN_SECRET: MySecret123
      PUBLIC_URL: http://localhost:5050
    build:
      context: .
      dockerfile: docker/auth.dockerfile
  proxy:
    image: nginx:stable-alpine
    ports:
      - "7070:80"
    volumes:
      - ./config/proxy.conf:/etc/nginx/templates/default.conf.template:ro
      - ./public:/var/www/html:ro
    environment:
      AUTH_SERVER_NAME: host.docker.internal
      AUTH_SERVER_PORT: 5050
      AUTH_SERVER_URL: http://localhost:5050
      REDIRECT_URL: http://localhost:7070
      CLIENT_ID: example-client-id